services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: simple123
      MYSQL_DATABASE: e_commerce_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: simple123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - e_com_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: simple123
      MYSQL_DATABASE: e_commerce_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - e_com_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - e_com_network
    restart: unless-stopped

networks:
  e_com_network:

volumes:
  mysql_data:
